version: '3.8'

services:
  web:
    build: .  # Usa o Dockerfile para construir a imagem
    container_name: camilacamargo-site
    restart: always
    ports:
      - "80:80"    # HTTP (para redirecionar para HTTPS)
      - "443:443"  # HTTPS
    volumes:
      - ./site:/usr/share/nginx/html  # Monta a pasta do site
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Config customizada (opcional)
      - certbot-etc:/etc/letsencrypt  # Certificados SSL
    networks:
      - web-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./site:/var/www/html  # Pasta para validação do SSL
    command: certonly --webroot --webroot-path=/var/www/html --email seu-email@dominio.com --agree-tos --no-eff-email -d camilacamargo.com.br -d www.camilacamargo.com.br
    depends_on:
      - web
    networks:
      - web-network

volumes:
  certbot-etc:

networks:
  web-network:
    driver: bridge